AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create EC2 and RDS instances

Parameters:
  EC2InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID of the Virtual Private Cloud (VPC)
    Default: vpc-0dc680ee23290e5b6  # Replace with your actual VPC ID

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: ID of the subnet for EC2 instances
    Default: subnet-0e41453c9b1028803  # Replace with your actual Subnet ID

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair for SSH access
    Default: demo-key  # Replace with your actual key pair name

  AMIId:
    Type: AWS::EC2::Image::Id
    Description: ID of the Amazon Machine Image (AMI) for EC2 instances
    Default: ami-03d294e37a4820c21  # Replace with your actual AMI ID

Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref EC2InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref AMIId
      SecurityGroups:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: "auto-stop"
          Value: "true"

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref EC2InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref AMIId
      SecurityGroups:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: "auto-stop"
          Value: "true"

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security Group
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp

  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t2.micro
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: "Admin123456"
      DBName: mydatabase
      MultiAZ: false
      Tags:
        - Key: "auto-stop"
          Value: "true"

Outputs:
  EC2Instance1PublicDNS:
    Description: Public DNS of EC2 instance 1
    Value: !GetAtt EC2Instance1.PublicDnsName

  EC2Instance2PublicDNS:
    Description: Public DNS of EC2 instance 2
    Value: !GetAtt EC2Instance2.PublicDnsName

  RDSInstanceEndpoint:
    Description: RDS instance endpoint
    Value: !GetAtt MyDBInstance.Endpoint.Address
